name: build

on:
  push:
    branches-ignore:
      - dependabot/*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: [4]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Download localisations
        uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
      - name: Install packages and symlink local dependencies
        run: |
          npm ci
      - name: Lint code
        run: |
          npm run lint
      - name: Run tests
        env:
          NODE_ENV: test
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_TOKEN_CREATE_SCOPE: ${{ secrets.TEST_TOKEN_CREATE_SCOPE }}
          TEST_TOKEN_NO_SCOPE: ${{ secrets.TEST_TOKEN_NO_SCOPE }}
          TEST_PUBLICATION_URL: https://getindiekit.github.io/sandbox/
          TEST_SESSION_SECRET: ${{ secrets.TEST_SESSION_SECRET }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
        run: |
          npm test
