name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4]
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Install packages and symlink local dependencies
      run: |
        npm install
    - name: Run tests
      env:
        TEST_PUBLICATION_URL: ${{ secrets.TEST_PUBLICATION_URL }}
        TEST_BEARER_TOKEN: ${{ secrets.TEST_BEARER_TOKEN }}
        TEST_BEARER_TOKEN_NOSCOPE: ${{ secrets.TEST_BEARER_TOKEN_NOSCOPE }}
      run: |
        npm test
